- example.js
- index.js
- package.json
> Override the default json parser

- index.js
- test.js
Fixes #8 
@yamalight can you please check if this solves your problem?
> add a slash if the prefix is equal to the url

- package.json
> chore(package): update make-promises-safe to version 3.0.0

- .gitignore
- index.d.ts
- package.json
- test/test.js
- test/types/index.ts
- test/types/tsconfig.json
Hi
It's a great plugin.
And we should make it accessible for TypeScript developers.
It's related to https://github.com/fastify/fastify-http-proxy/issues/54
> Add types definition for TS integration

- package.json
> chore(package): update @types/node to version 12.6.2

- package.json
> ignore got@10

- .travis.yml
- package.json
- test/test.js
> Updated deps, droppped Node 8

- package.json
> chore(package): update got to version 10.6.0

- README.md
- index.d.ts
- index.js
- test/test.js
> Add `proxyPayloads` option

- README.md
- index.js
- package.json
- test/websocket.js
This PR adds basic support for WebSockets. It does not mean to be complete but rather a guide for other contributors that are interested in finishing this feature.
> Added basic websocket support

- index.d.ts
- package.json
- test/index.test-d.ts
This fixes the issues discussed in #100
> Fixes types and adds typescript tests to CI

- index.d.ts
- test/index.test-d.ts
- test/test.js
- [-] documentation is changed or added
> Use types from fastify-reply-from. fix #102

- README.md
> chore: update version requirement in readme

- .dependabot/config.yml
- .github/dependabot.yml
- .github/workflows/ci.yml
> chore: add dependabot auto merge

- test/ws-prefix-rewrite.js
> faster ws-prefix-rewrite test

- .taprc
- package.json
- test/socket.io.js
- test/test.js
- test/websocket.js
- test/ws-prefix-rewrite-core.js
- test/ws-prefix-rewrite.js
> Updated tap@15

- index.js
- test/test.js
Address: https://github.com/fastify/fastify-http-proxy/issues/204﻿
> fix: prevent internal error when qs is sent

- README.md
The module name has changed, so the installation instructions and sample code needs to be updated to match.
> docs: update installation instructions etc.

- .github/workflows/ci.yml
- index.js
- package.json
- test/socket.io.js
- test/test.js
- test/websocket.js
- test/ws-prefix-rewrite-core.js
- test/ws-prefix-rewrite.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
> Update to Fastify v4

- README.md
- benchmarks/fast-proxy.js
- benchmarks/fastify-proxy.js
- benchmarks/origin.js
- examples/example.js
> chore: replace use of deprecated variadic `listen()`

- README.md
Signed-off-by: Matteo Collina <hello@matteocollina.com>
Fixes #262 
> Add note on the README about Fastify v4

- index.js
- test/test.js
Adds the ability to handled placeholders in prefixed paths (#265)
> Add ability to handle variables in prefixed paths

- README.md
> fix: @fastify/http-proxy v7.x link

- index.js
- package.json
Use fastify-plugin instead of patching directly the metadata this pull request is made for fix issue #280 
> use fastify-plugin instead of patching directly the metadata

- package.json
> Bumped @fastify/reply-from to v9

- types/index.test-d.ts
> fix types tests after undici update

- test/websocket.js
See https://github.com/fastify/fastify/pull/5057
> test(websocket): optimize split param
