fastify/fastify-http-proxy

index.js

Changed `request.raw` to `request.req` in order to provide backwards compatibility for pre-v1 versions of Fastify.

Bugfix: backwards compatibility for fastify 0.x.

---

test.js

Added a test to make sure that ambigous/overlapping prefixes does not collide or generate unexpected behaviors
References #10

Improved test suite with test to check ambigous/overlapping prefixes

---

README.md
index.js
test.js

Adds support for `rewriteHeaders`, `onResponse`, `queryString` and other options from fastify-reply-from 
https://github.com/fastify/fastify-reply-from#replyfromsource-opts

feat: support reply options

---

README.md
index.js
test.js

Fixes https://github.com/fastify/fastify-http-proxy/issues/23.
@clarkorz can you check if this works for you?

Added keepProxy to not rewrite the URL.

---

README.md
index.js
package.json

Follow up to https://github.com/fastify/fastify-http-proxy/pull/31:
Rebased on master with feedback

Replace basePath with prefix for Fastify v2 compatibility

---

README.md
index.js
test.js

Fastify core is complaining Warning: The route option `beforeHandler`
has been deprecated, use `preHandler` instead.
This commit change the `beforeHandler` to `preHandler`

replace beforeHandler with preHandler

---

README.md
index.js
test.js

As titled. It is possible that a user may need to pass in context to their `preHandler`. This PR makes it possible.

Add support for passing in extra configuration

---

package.json

Caught this testing fastify `next` versions, this module currently installs fastify-plugin 1.x and 2.x.  Upgrading fastify-websocket here eliminates fastify-plugin 1.x.

Bump fastify-websocket from 1.1.2 to 2.0.1

---

README.md

`upstream` is passed as `base` to `fastify-reply-from`. Quoting `fastify-reply-form` doc:
> *base*
> Set the base URL for all the forwarded requests. Will be required if http2 is set to true Note that path will be discarded.
So, specifying `/auth` in `upstream` has no effect at all, but this example seems to suggest `/auth/user` requests will be forwarded to `http://single-signon.example.com/auth/user`, when the real target will be `http://single-signon.example.com/user`.

README: Corrected confusing example

---

package.json
test/test.js

Added a regression test to cover for https://github.com/mcollina/undici/pull/270

Added regression test with undici with a body

---

benchmarks/fast-proxy.js
package.json

Hi. Thanks for the nice tool.
I recently use this in my work and I find out that there are some proxy plugins here. Seem's this one and fast-proxy are both under fastify org. So I'm interested in the benchmark result and add the benchmark here since this plugin looks more officially.
I haven't change the benchmark result in README since it depends on the running machine and you may update it. :)

Add fast proxy benchmark

---

README.md

Added an example with request tracking as discussed in #80

Add tracking `request-id` example

---

README.md
index.d.ts
index.js
package.json
test/socket.io.js
test/test.js
test/websocket.js

- Remove `fastify-websocket`: proxy `ws` events directly.
- Proxy query string with WebSockets.
- Support `prefix` and `rewritePrefix` options with WebSockets.
- Support custom `ws` options for both client and server.
- Add `socket.io` tests.

Remove fastify-websocket, proxy ws events directly

---

index.d.ts
test/index.test-d.ts

Current typings for `replyOptions` are coarse. This pull request improves on the existing typings by giving `replyOptions` the type `FastifyReplyFromHooks` (https://github.com/fastify/fastify-reply-from/blob/master/index.d.ts#L32), which appears to be the right type considering how `replyOptions` is used in this package:
https://github.com/fastify/fastify-http-proxy/blob/master/index.js#L159
Closes https://github.com/fastify/fastify-http-proxy/issues/126
Note: this is a **breaking change**. Existing consumers of the package might be passing properties to `replyOptions` that are not in `FastifyReplyFromHooks`. They'll result in a type error once this PR is merged.

improve typings for replyOptions

---

index.js
test/websocket.js

Fixes https://github.com/fastify/fastify-http-proxy/issues/130

fix: capture websocket server errors

---

example.js
index.js
test/test.js

Allow absolute URL redirects when applicable. Closes #124 .

Allow passthrough redirects

---

README.md
index.d.ts
index.js
test/index.test-d.ts
test/test.js

Added setting of methods for proxying

---

.github/workflows/ci.yml
package.json

`undici` v4 dropping support of node v10, and `fastify-reply-from` v6 relies on that.
`fastify-http-proxy` also affected by this after #162.
I am experiencing something similar to #136 currently, so I hope to use  `undici` v4's `strictContentLength` option in the next major release 😄 
ref: 
* https://github.com/fastify/fastify-reply-from/pull/179
* https://github.com/nodejs/undici/releases/tag/v4.0.0

feat: drop node v10 support

---

index.js
package.json
test/export.js

Fixes: #169 
add `default` and `named` export.

feat: add default and named export

---

index.js
package.json
test/utils.js
test/websocket.js
test/ws-prefix-rewrite-core.js
test/ws-prefix-rewrite.js
utils.js

`ws@8.0.0` introduces a breaking change that throws a `SyntaxError` when calling `new WebSocket()` with an URL with `http://` protocol. 
This PR fixes such issue, forcing when needed the `ws://` protocol instead.

force `ws://` protocol when instantiating a new `WebSocket`

---

index.d.ts
index.js
test/index.test-d.ts
test/test.js

Add constraints option

---

README.md
examples/example.js
index.d.ts
package.json
test/index.test-d.ts
test/types/index.test-d.ts

Hello.
This PR aims to :
- fix a failing typescript definition test
- update typescript definitions and tests
- upgrade package dependencies
- harmonize directory structure
Superseed https://github.com/fastify/fastify-http-proxy/pull/225, https://github.com/fastify/fastify-http-proxy/pull/221, https://github.com/fastify/fastify-http-proxy/pull/215

fix (types): update typescript definitions, typescript tests and harmonize directory structure

---

package.json
test/types/index.test-d.ts

Fixes: #239 
Related to https://github.com/fastify/fastify-reply-from/pull/234
For who curious why it is removed.

test: update type test

---

README.md
index.js
test/websocket.js

I was planning to forward all the headers, but then I got the `Invalid Sec-WebSocket-Accept header` error, so I decided starting only forwarding the cookies.
I tested this with https://github.com/pearofducks/rollup-plugin-dev, and the cookie forwarding seems to be working as expected!
Let me know if you know how to fix the `Invalid Sec-WebSocket-Accept header`, and I can update this PR or create a new one. Maybe we should forward all the header with exception of the "sec-websocket-*" headers??.
Thanks in advance

feat: forward cookies to websocket proxy

---

README.md
index.js
test/test.js

rewritePrefix is currently ignored if prefix isn't filled in. This isn't documented and caused me struggles without reading the source code.

Allow rewritePrefix without having to need prefix

---

README.md
index.js
test/websocket.js

This PR updates WebSocket proxy feature to pass the subprotocol, as indicated by the client in `Sec-WebSocket-Protocol` header, to the upstream WebSocket server.
This change is necessary for proxying GraphQL WebSocket connections, in which the server often checks the subprotocol header.
A limitation of this implementation is that, if the incoming `Sec-WebSocket-Protocol` header contains multiple subprotocols, the proxy always picks the first subprotocol, and does not give upstream server an opportunity to make this choice.
This limitation is caused by `WebSocketServer` option `handleProtocols` being a synchronous function, in which it's impossible to pass the list of subprotocols and allow the upstream to make a choice.
and the [Code of …

Pass WebSocket subprotocol to upstream

---

index.js
test/websocket.js

fixes #255
One more change needed for GraphQL proxy to work.
I have tested this with `graphql-request` client.

Preserve text vs binary frames

---

index.js
test/test.js

The `rewriteHeaders` callback of `fastify-reply-from` can receive a request as an argument. But the `rewriteHeaders` callback overwritten by `fastify-http-proxy` doesn't forward the request. Fixed this issue.

feat: add request argument to rewriteHeaders

---

README.md

The route config link still points to document for fastify 2.1.x.
This MR modifies the link to 4.8.x (since there is no link for major version `4.x`).
It's slightly better than just pointing to `latest` as this plugin might not be compatible with the future fastify version (e.g. v5) right away.

docs(readme): fix route config link

---

index.js
test/test.js
test/websocket.js

Signed-off-by: Matteo Collina <hello@matteocollina.com>

Added WebSocket support for getUpstream()

---

.taprc
README.md
index.js
test/websocket.js
test/ws-prefix-rewrite-core.js

Run hooks with websockets and rewrite ws headers

---

README.md
index.js
test/test.js

This PR adds support for parametric path with both `prefix` and `rewritePrefix`
Example:
```javascript
// /rest-api/123/endpoint will be proxied to http://my-rest-api.example.com/123/endpoint
server.register(proxy, {
upstream: 'http://my-rest-api.example.com',
prefix: '/rest-api/:id/endpoint', // optional
rewritePrefix: '/:id/endpoint', // optional
http2: false // optional
})
```

Added support for parametric rewrite prefix

---

README.md
index.js
test/test.js

fixes: https://github.com/fastify/fastify-http-proxy/issues/296

feat: add internalRewriteLocationHeader option

---

README.md

docs(readme): update outdated fastify-reply-from link

---

test/socket.io.js
test/websocket.js

Listen only to IPv4 network for websockets tests

---

README.md
index.js
test/test.js
types/index.d.ts
types/index.test-d.ts

Provide an option to preValidate incoming data (check out: https://github.com/fastify/fastify-http-proxy/issues/311)

opt to validate incoming data before proxy is executed

---

benchmarks/http-proxy.js
index.js
test/socket.io.js
test/test.js
test/websocket.js
test/ws-prefix-rewrite-core.js
test/ws-prefix-rewrite.js

See https://github.com/fastify/fastify-static/pull/407

perf: use `node:` prefix to bypass require.cache call for builtins

---

index.js
package.json
test/test.js

keep query params on proxy

---

README.md
examples/example.js
test/test.js

See https://github.com/fastify/ajv-compiler/pull/115

chore: replace `fastify.io` links with `fastify.dev`

---

README.md
index.js
test/websocket.js

Fixes 2 issues:
- mismatch between Http and WebSocket routing
- WebSockets now support constraints
- WebSockets now use the same path rewriting logic as Http
- `wsServerOptions` are now distinct for each WebSocket proxy
Fixes: #206 

Add WebSocket host constraints

---

types/index.d.ts
types/index.test-d.ts

Hello,
The `internalRewriteLocationHeader` was added some months ago, it's working fine but the TS types had not been updated, so this is a quick PR to add it

chore(types): add internalRewriteLocationHeader in ts types

---

package.json
test/test.js

make-promises-safe doesn't appear to have actually been in use.
I also updated a test that was access the deprecated `reply.context.config`

chore: remove unused make-promises-safe

---

index.js
test/websocket.js

Please understand if there is something I don't understand.
This is a fix for the part where the websocket path cannot be passed as is.
I have added the example and proxying part below.
for example)
wsUpstream: ws://localhost:3030
1. ws://proxyhost/keep/path > ws://localhost:3030/keep/path
2. ws://proxyhost/keep2/path > ws://localhost:3030/keep2/path

Keep websocket path on proxy

---

index.js
test/websocket-querystring.js
types/index.d.ts
types/index.test-d.ts

Allow overriding or modifying the queryString when proxying websockets.
Fixes: #348

feat: allow overriding or modifying the queryString for websockets

---

index.js
test/websocket.js

Resolves #333 
This fix makes using `wsUpstream: ''` with a set `replyOptions.getUpstream` consistent with the established flow of using `upstream: ''` with a `getUpstream` set. To do so, just some added logic to the plugin initialization phase as well as updating the WebsocketProxy constructor logic. Note, I maintained the need for the `websocket` flag needing to be set to `true` to remain consistent with the proxying of websockets currently.
This should also allow for dynamically setting a websocket upstream through the use of the websocket options provided, which should be a bit more clear for those wanting that behavior.

fix:  allow for getUpstream flow for empty wsUpstream option
